// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sql

import (
	"database/sql"
	"time"
)

type Customer struct {
	CustomerID            interface{}
	CustomerUniqueID      string
	CustomerZipCodePrefix int64
	CustomerCity          string
	CustomerState         string
}

type Geolocation struct {
	GeolocationZipCodePrefix int64
	GeolocationLat           float64
	GeolocationLng           float64
	GeolocationCity          string
	GeolocationState         string
}

type LeadsClosed struct {
	MqlID                      int64
	SellerID                   int64
	SdrID                      int64
	SrID                       int64
	WonDate                    time.Time
	BusinessSegment            string
	LeadType                   string
	LeadBehaviourProfile       string
	HasCompany                 bool
	HasGtin                    bool
	AverageStock               int64
	BusinessType               string
	DeclaredProductCatalogSize int64
	DeclaredMonthlyRevenue     float64
}

type LeadsQualified struct {
	MqlID            interface{}
	FirstContactDate time.Time
	LandingPageID    int64
	Origin           string
}

type Order struct {
	OrderID                    interface{}
	CustomerID                 int64
	OrderStatus                string
	OrderPurchaseTimestamp     time.Time
	OrderApprovedAt            sql.NullTime
	OrderDeliveredCarrierDate  sql.NullTime
	OrderDeliveredCustomerDate sql.NullTime
	OrderEstimatedDeliveryDate sql.NullTime
}

type OrderItem struct {
	OrderID           int64
	OrderItemID       int64
	ProductID         int64
	SellerID          int64
	ShippingLimitDate time.Time
	Price             float64
	FreightValue      float64
}

type OrderPayment struct {
	OrderID             int64
	PaymentSequential   int64
	PaymentType         string
	PaymentInstallments int64
	PaymentValue        float64
}

type OrderReview struct {
	ReviewID              interface{}
	OrderID               int64
	ReviewScore           int64
	ReviewCommentTitle    sql.NullString
	ReviewCommentMessage  sql.NullString
	ReviewCreationDate    time.Time
	ReviewAnswerTimestamp sql.NullTime
}

type Product struct {
	ProductID                interface{}
	ProductCategoryName      string
	ProductNameLength        int64
	ProductDescriptionLength int64
	ProductPhotosQty         int64
	ProductWeightG           int64
	ProductLengthCm          int64
	ProductHeightCm          int64
	ProductWidthCm           int64
}

type ProductCategoryNameTranslation struct {
	ProductCategoryName        string
	ProductCategoryNameEnglish string
}

type Seller struct {
	SellerID            interface{}
	SellerZipCodePrefix int64
	SellerCity          string
	SellerState         string
}
